const ingredients = [
  { name: 'Tomato', category: 'Vegetables', unit: 'grams', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
  { name: 'Onion', category: 'Vegetables', unit: 'grams', calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1 },
  { name: 'Garlic', category: 'Vegetables', unit: 'cloves', calories: 149, protein: 6.4, carbs: 33, fat: 0.5 },
  { name: 'Ginger', category: 'Vegetables', unit: 'grams', calories: 80, protein: 1.8, carbs: 18, fat: 0.8 },
  { name: 'Chicken', category: 'Proteins', unit: 'grams', calories: 239, protein: 27, carbs: 0, fat: 14 },
  { name: 'Rice', category: 'Grains & Bakery', unit: 'grams', calories: 130, protein: 2.7, carbs: 28, fat: 0.3 },
  { name: 'Potato', category: 'Vegetables', unit: 'grams', calories: 77, protein: 2, carbs: 17, fat: 0.1 },
  { name: 'Carrot', category: 'Vegetables', unit: 'grams', calories: 41, protein: 0.9, carbs: 10, fat: 0.2 },
  { name: 'Paneer', category: 'Dairy', unit: 'grams', calories: 265, protein: 18, carbs: 6, fat: 20, isAllergen: true, allergenType: 'Dairy' },
  { name: 'Milk', category: 'Dairy', unit: 'ml', calories: 42, protein: 3.4, carbs: 5, fat: 1, isAllergen: true, allergenType: 'Dairy' },
  { name: 'Egg', category: 'Proteins', unit: 'pieces', calories: 155, protein: 13, carbs: 1.1, fat: 11, isAllergen: true, allergenType: 'Eggs' },
  { name: 'Cheese', category: 'Dairy', unit: 'grams', calories: 402, protein: 25, carbs: 1.3, fat: 33, isAllergen: true, allergenType: 'Dairy' },
  { name: 'Butter', category: 'Dairy', unit: 'grams', calories: 717, protein: 0.9, carbs: 0.1, fat: 81, isAllergen: true, allergenType: 'Dairy' },
  { name: 'Olive Oil', category: 'Pantry & Spices', unit: 'ml', calories: 884, protein: 0, carbs: 0, fat: 100 },
  { name: 'Spinach', category: 'Vegetables', unit: 'grams', calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  { name: 'Mushroom', category: 'Vegetables', unit: 'grams', calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3 },
  { name: 'Capsicum', category: 'Vegetables', unit: 'grams', calories: 31, protein: 1, carbs: 6, fat: 0.3 },
  { name: 'Cumin', category: 'Pantry & Spices', unit: 'grams', calories: 375, protein: 18, carbs: 44, fat: 22 },
  { name: 'Coriander', category: 'Pantry & Spices', unit: 'grams', calories: 298, protein: 12, carbs: 55, fat: 18 },
  { name: 'Turmeric', category: 'Pantry & Spices', unit: 'grams', calories: 312, protein: 9.7, carbs: 67, fat: 3.3 },
  { name: 'Chilli Powder', category: 'Pantry & Spices', unit: 'grams', calories: 282, protein: 12, carbs: 50, fat: 14 },
  { name: 'Garam Masala', category: 'Pantry & Spices', unit: 'grams', calories: 379, protein: 10, carbs: 58, fat: 15 },
  { name: 'Lemon', category: 'Fruits', unit: 'pieces', calories: 29, protein: 1.1, carbs: 9.3, fat: 0.3 },
  { name: 'Yoghurt', category: 'Dairy', unit: 'grams', calories: 59, protein: 10, carbs: 3.6, fat: 0.4, isAllergen: true, allergenType: 'Dairy' },
  { name: 'Bread', category: 'Grains & Bakery', unit: 'slices', calories: 265, protein: 9, carbs: 49, fat: 3.2, isAllergen: true, allergenType: 'Gluten' },
  { name: 'Pasta', category: 'Grains & Bakery', unit: 'grams', calories: 131, protein: 5, carbs: 25, fat: 1.1, isAllergen: true, allergenType: 'Gluten' },
  { name: 'Peas', category: 'Vegetables', unit: 'grams', calories: 81, protein: 5.4, carbs: 14, fat: 0.4 },
  { name: 'Corn', category: 'Vegetables', unit: 'grams', calories: 86, protein: 3.2, carbs: 19, fat: 1.2 },
  { name: 'Cabbage', category: 'Vegetables', unit: 'grams', calories: 25, protein: 1.3, carbs: 6, fat: 0.1 },
  { name: 'Cauliflower', category: 'Vegetables', unit: 'grams', calories: 25, protein: 1.9, carbs: 5, fat: 0.3 },
  { name: 'Green Beans', category: 'Vegetables', unit: 'grams', calories: 31, protein: 1.8, carbs: 7, fat: 0.1 },
  { name: 'Curry Leaves', category: 'Pantry & Spices', unit: 'grams', calories: 108, protein: 6.1, carbs: 18.7, fat: 1 },
  { name: 'Mustard Seeds', category: 'Pantry & Spices', unit: 'grams', calories: 508, protein: 26, carbs: 28, fat: 36 },
  { name: 'Black Pepper', category: 'Pantry & Spices', unit: 'grams', calories: 251, protein: 10, carbs: 64, fat: 3.3 },
  { name: 'Salt', category: 'Pantry & Spices', unit: 'grams', calories: 0, protein: 0, carbs: 0, fat: 0 },
  { name: 'Sugar', category: 'Pantry & Spices', unit: 'grams', calories: 387, protein: 0, carbs: 100, fat: 0 },
  { name: 'Honey', category: 'Pantry & Spices', unit: 'grams', calories: 304, protein: 0.3, carbs: 82, fat: 0 },
  { name: 'Oats', category: 'Grains & Bakery', unit: 'grams', calories: 389, protein: 17, carbs: 66, fat: 7 },
  { name: 'Chickpeas', category: 'Proteins', unit: 'grams', calories: 164, protein: 9, carbs: 27, fat: 2.6 },
  { name: 'Coconut Milk', category: 'Dairy', unit: 'ml', calories: 230, protein: 2.3, carbs: 5.5, fat: 24 },
  { name: 'Soy Sauce', category: 'Pantry & Spices', unit: 'tbsp', calories: 15, protein: 1.5, carbs: 1, fat: 0, isAllergen: true, allergenType: 'Soy' },
  { name: 'Flour', category: 'Grains & Bakery', unit: 'grams', calories: 364, protein: 10, carbs: 76, fat: 1, isAllergen: true, allergenType: 'Gluten' },
  { name: 'Noodles', category: 'Grains & Bakery', unit: 'grams', calories: 138, protein: 4.5, carbs: 25, fat: 2, isAllergen: true, allergenType: 'Gluten' }
];

export default ingredients;